/** ISO 3166-1 numeric country codes → English name + flag emoji */
const COUNTRIES = {
    4: ['Afghanistan', '🇦🇫'],
    8: ['Albania', '🇦🇱'],
    12: ['Algeria', '🇩🇿'],
    20: ['Andorra', '🇦🇩'],
    24: ['Angola', '🇦🇴'],
    32: ['Argentina', '🇦🇷'],
    36: ['Australia', '🇦🇺'],
    40: ['Austria', '🇦🇹'],
    48: ['Bahrain', '🇧🇭'],
    50: ['Bangladesh', '🇧🇩'],
    56: ['Belgium', '🇧🇪'],
    68: ['Bolivia', '🇧🇴'],
    70: ['Bosnia and Herzegovina', '🇧🇦'],
    76: ['Brazil', '🇧🇷'],
    100: ['Bulgaria', '🇧🇬'],
    112: ['Belarus', '🇧🇾'],
    124: ['Canada', '🇨🇦'],
    152: ['Chile', '🇨🇱'],
    156: ['China', '🇨🇳'],
    170: ['Colombia', '🇨🇴'],
    188: ['Costa Rica', '🇨🇷'],
    191: ['Croatia', '🇭🇷'],
    196: ['Cyprus', '🇨🇾'],
    203: ['Czechia', '🇨🇿'],
    208: ['Denmark', '🇩🇰'],
    214: ['Dominican Republic', '🇩🇴'],
    218: ['Ecuador', '🇪🇨'],
    233: ['Estonia', '🇪🇪'],
    246: ['Finland', '🇫🇮'],
    250: ['France', '🇫🇷'],
    268: ['Georgia', '🇬🇪'],
    276: ['Germany', '🇩🇪'],
    300: ['Greece', '🇬🇷'],
    320: ['Guatemala', '🇬🇹'],
    344: ['Hong Kong', '🇭🇰'],
    348: ['Hungary', '🇭🇺'],
    352: ['Iceland', '🇮🇸'],
    356: ['India', '🇮🇳'],
    360: ['Indonesia', '🇮🇩'],
    372: ['Ireland', '🇮🇪'],
    376: ['Israel', '🇮🇱'],
    380: ['Italy', '🇮🇹'],
    392: ['Japan', '🇯🇵'],
    398: ['Kazakhstan', '🇰🇿'],
    410: ['South Korea', '🇰🇷'],
    428: ['Latvia', '🇱🇻'],
    440: ['Lithuania', '🇱🇹'],
    442: ['Luxembourg', '🇱🇺'],
    458: ['Malaysia', '🇲🇾'],
    484: ['Mexico', '🇲🇽'],
    498: ['Moldova', '🇲🇩'],
    504: ['Morocco', '🇲🇦'],
    528: ['Netherlands', '🇳🇱'],
    554: ['New Zealand', '🇳🇿'],
    578: ['Norway', '🇳🇴'],
    586: ['Pakistan', '🇵🇰'],
    604: ['Peru', '🇵🇪'],
    608: ['Philippines', '🇵🇭'],
    616: ['Poland', '🇵🇱'],
    620: ['Portugal', '🇵🇹'],
    630: ['Puerto Rico', '🇵🇷'],
    642: ['Romania', '🇷🇴'],
    643: ['Russia', '🇷🇺'],
    682: ['Saudi Arabia', '🇸🇦'],
    688: ['Serbia', '🇷🇸'],
    702: ['Singapore', '🇸🇬'],
    703: ['Slovakia', '🇸🇰'],
    705: ['Slovenia', '🇸🇮'],
    710: ['South Africa', '🇿🇦'],
    724: ['Spain', '🇪🇸'],
    752: ['Sweden', '🇸🇪'],
    756: ['Switzerland', '🇨🇭'],
    158: ['Taiwan', '🇹🇼'],
    764: ['Thailand', '🇹🇭'],
    792: ['Turkey', '🇹🇷'],
    804: ['Ukraine', '🇺🇦'],
    784: ['United Arab Emirates', '🇦🇪'],
    826: ['United Kingdom', '🇬🇧'],
    840: ['United States', '🇺🇸'],
    858: ['Uruguay', '🇺🇾'],
    862: ['Venezuela', '🇻🇪'],
    704: ['Vietnam', '🇻🇳'],
};

function formatCountry(code) {
    if (code == null || code === 0) return 'Unknown';
    const entry = COUNTRIES[code];
    if (!entry) return `Country ${code}`;
    return `${entry[1]} ${entry[0]}`;
}

module.exports = { formatCountry };
